Repository NREL/GEOPHIRES-X, pull requests merged in 2023-11, with the labels that each got.

#26 Reference Manual (Parameters) + README cleanup
  .bumpversion.cfg
  .cookiecutterrc
  .github/workflows/github-actions.yml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  AUTHORS.rst
  CONTRIBUTING.rst
  How-to-extend-GEOPHIRES-X.md
  MANIFEST.in
  README.rst
  References/Theoretical basis for geophires.pdf
  ci/templates/.github/workflows/github-actions.yml
  docs/How-to-extend-GEOPHIRES-X.md
  docs/conf.py
  docs/index.rst
  docs/overview.rst
  docs/reference/geophires_x.rst
  docs/reference/geophires_x_client.rst
  docs/reference/index.rst
  docs/requirements.txt
  docs/spelling_wordlist.txt
  docs/templates/layout.html
  pyproject.toml
  setup.py
  src/geophires_x/AdvModel.py
  src/geophires_x/CylindricalReservoir.py
  src/geophires_x/EconomicsAddOns.py
  src/geophires_x/Model.py
  src/geophires_x/WellBores.py
  src/geophires_x/__init__.py
  src/geophires_x/conf.py
  src/geophires_x/index.rst
  src/geophires_x_client/geophires_x_result.py
  src/geophires_x_schema_generator/__init__.py
  src/geophires_x_schema_generator/main.py
  src/hip_ra/HIP_RA.py
  tests/__init__.py
  tests/examples/HIPexample1.out
  tests/test_HIP_RA.py
  tests/test_geophires_x.py
  tests/test_geophires_x_client.py
  tests/test_geophires_x_schema_generator.py
  tox.ini
Labels: documentation, enhancement

#30 Add Windows to test matrix; fix Windows unit test failure
  .github/workflows/github-actions.yml
  src/hip_ra/HIP_RA.py
  tests/base_test_case.py
Labels: bug

#45 No functional changes. Only Docstring changes and formatting. removed…
  .gitignore
  src/geophires_x/AGSEconomics.py
  src/geophires_x/AGSOutputs.py
  src/geophires_x/AGSSurfacePlant.py
  src/geophires_x/AGSWellBores.py
  src/geophires_x/CLEconomics.py
  src/geophires_x/CLOutputs.py
  src/geophires_x/CLWellBores.py
  src/geophires_x/CylindricalReservoir.py
  src/geophires_x/Economics.py
  src/geophires_x/EconomicsAddOns.py
  src/geophires_x/EconomicsCCUS.py
  src/geophires_x/EconomicsS_DAC_GT.py
  src/geophires_x/GEOPHIRESv3.py
  src/geophires_x/GeoPHIRESUtils.py
  src/geophires_x/LHSReservoir.py
  src/geophires_x/MC_GeoPHIRES3.py
  src/geophires_x/MPFReservoir.py
  src/geophires_x/Model.py
  src/geophires_x/Outputs.py
  src/geophires_x/OutputsAddOns.py
  src/geophires_x/OutputsCCUS.py
  src/geophires_x/OutputsS_DAC_GT.py
  src/geophires_x/Parameter.py
  src/geophires_x/Reservoir.py
  src/geophires_x/SFReservoir.py
  src/geophires_x/SurfacePlant.py
  src/geophires_x/TDPReservoir.py
  src/geophires_x/TOUGH2Reservoir.py
  src/geophires_x/UPPReservoir.py
  src/geophires_x/WellBores.py
Labels: documentation

#47 SUTRA fields result parsing; CONTRIBUTING.rst cleanup; SUTRA example in extension guide
  .bumpversion.cfg
  .cookiecutterrc
  AUTHORS.rst
  CONTRIBUTING.rst
  README.rst
  docs/How-to-extend-GEOPHIRES-X.md
  docs/conf.py
  setup.py
  src/geophires_x/AGSEconomics.py
  src/geophires_x/AGSSurfacePlant.py
  src/geophires_x/AGSWellBores.py
  src/geophires_x/AdvGeoPHIRESUtils.py
  src/geophires_x/SUTRAOutputs.py
  src/geophires_x/__init__.py
  src/geophires_x_client/geophires_x_result.py
  tests/test_geophires_x.py
  tests/test_geophires_x_schema_generator.py
Labels: documentation
