Repository NREL/GEOPHIRES-X, pull requests merged in 2024-09, with the labels that each got.

#284 SBT integration
  src/geophires_x/Economics.py
  src/geophires_x/Model.py
  src/geophires_x/OptionList.py
  src/geophires_x/Outputs.py
  src/geophires_x/Reservoir.py
  src/geophires_x/SBTEconomics.py
  src/geophires_x/SBTReservoir.py
  src/geophires_x/SBTWellbores.py
  src/geophires_x/SurfacePlant.py
  src/geophires_x/Units.py
  src/geophires_x/WellBores.py
  tests/examples/example_SBT_Hi_T.out
  tests/examples/example_SBT_Hi_T.txt
  tests/examples/example_SBT_Lo_T.out
  tests/examples/example_SBT_Lo_T.txt
Labels: enhancement

#286 SBT docs, version bump
  .bumpversion.cfg
  .cookiecutterrc
  CHANGELOG.rst
  CONTRIBUTING.rst
  README.rst
  docs/conf.py
  docs/reference/geophires_x.rst
  setup.py
  src/geophires_x/Units.py
  src/geophires_x/__init__.py
  src/geophires_x_client/geophires_x_result.py
  tests/test_geophires_x.py
Labels: documentation

#293 Documentation fixes/updates - HIP-RA-X, Examples
  README.rst
  src/geophires_x/Units.py
  src/geophires_x_schema_generator/hip-ra-x-request.json
  src/hip_ra_x/hip_ra_x.py
  tests/examples/Fervo_Project_Cape.txt
  tests/hip_ra_x_tests/examples/HIP-RA-X_example1.out
Labels: documentation, feature request

#295 Fix list parameters
  .bumpversion.cfg
  .cookiecutterrc
  README.rst
  docs/conf.py
  setup.py
  src/geophires_x/GeoPHIRESUtils.py
  src/geophires_x/Parameter.py
  src/geophires_x/Reservoir.py
  src/geophires_x/SBTReservoir.py
  src/geophires_x/__init__.py
  tests/examples/example_multiple_gradients-2.out
  tests/examples/example_multiple_gradients-2.txt
  tests/geophires_x_client_tests/input_comments.txt
  tests/test_geophires_utils.py
Labels: bug
