Repository NREL/GEOPHIRES-X, pull requests merged in 2024-04, with the labels that each got.

#178 Fix MC HIP-RA test
  src/geophires_monte_carlo/MC_GeoPHIRES3.py
  src/geophires_monte_carlo/__init__.py
  src/geophires_x/.gitignore
  tests/.gitignore
  tests/geophires_monte_carlo_tests/MC_HIP_Settings_file.txt
  tests/geophires_monte_carlo_tests/test_geophires_monte_carlo.py
Labels: bug

#182 Unit test for MC HIP-RA-X
  .bumpversion.cfg
  .cookiecutterrc
  README.rst
  docs/conf.py
  setup.py
  src/geophires_monte_carlo/MC_GeoPHIRES3.py
  src/geophires_x/Reservoir.py
  src/geophires_x/__init__.py
  src/geophires_x_schema_generator/.gitignore
  tests/geophires_monte_carlo_tests/HIP-RA-X_example1.txt
  tests/geophires_monte_carlo_tests/MC_HIP-RA-X_Settings_file.txt
  tests/geophires_monte_carlo_tests/test_geophires_monte_carlo.py
Labels: enhancement

#177 Adding rich HTML output for All of GEOPHIRES.
  src/geophires_monte_carlo/Examples/MC_HIP_Settings_file.txt
  src/geophires_monte_carlo/MC_GeoPHIRES3.py
  src/geophires_x/.gitignore
  src/geophires_x/Economics.py
  src/geophires_x/GEOPHIRESv3.py
  src/geophires_x/GeoPHIRESUtils.py
  src/geophires_x/Outputs.py
  src/geophires_x/OutputsAddOns.py
  src/geophires_x/OutputsS_DAC_GT.py
  src/geophires_x_client/geophires_x_result.py
  tests/example1_addons.csv
  tests/examples/S-DAC-GT.out
  tests/examples/S-DAC-GT.txt
  tests/examples/Wanju_Yuan_Closed-Loop_Geothermal_Energy_Recovery.out
  tests/examples/example1.out
  tests/examples/example10_HP.out
  tests/examples/example11_AC.out
  tests/examples/example12_DH.out
  tests/examples/example13.out
  tests/examples/example1_addons.out
  tests/examples/example2.out
  tests/examples/example3.out
  tests/examples/example4.out
  tests/examples/example5.out
  tests/examples/example8.out
  tests/examples/example9.out
  tests/examples/example_ITC.out
  tests/examples/example_ITC.txt
  tests/examples/example_PTC.out
  tests/examples/example_PTC.txt
  tests/examples/example_SHR-1.out
  tests/examples/example_SHR-2.out
  tests/examples/example_multiple_gradients.out
  tests/test_geophires_x_client.py
Labels: enhancement

#165 updated well drill cost correlations
  src/geophires_x/Economics.py
  src/geophires_x/OptionList.py
  src/geophires_x/SUTRAEconomics.py
  src/geophires_x_schema_generator/geophires-request.json
  tests/example1_addons.csv
  tests/examples/example1.out
  tests/examples/example10_HP.out
  tests/examples/example11_AC.out
  tests/examples/example12_DH.out
  tests/examples/example13.out
  tests/examples/example1_addons.out
  tests/examples/example1_addons.txt
  tests/examples/example2.out
  tests/examples/example3.out
  tests/examples/example4.out
  tests/examples/example5.out
  tests/examples/example9.out
  tests/examples/example_ITC.out
  tests/examples/example_PTC.out
  tests/examples/example_SHR-2.out
  tests/examples/example_SHR-2.txt
  tests/examples/example_multiple_gradients.out
  tests/test_geophires_x_client.py
Labels: enhancement

#190 Editable installation update instructions
  README.rst
Labels: documentation, enhancement
