Repository NREL/GEOPHIRES-X, pull requests merged in 2024-06, with the labels that each got.

#229 Add Windows instructions for Virtual Environment to CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: documentation

#240 Add Estimated Jobs Created for electricity end-use
  .bumpversion.cfg
  .cookiecutterrc
  README.rst
  docs/conf.py
  setup.py
  src/geophires_x/Economics.py
  src/geophires_x/Outputs.py
  src/geophires_x/__init__.py
  src/geophires_x_client/geophires_x_result.py
  tests/example1_addons.csv
  tests/examples/Fervo_Norbeck_Latimer_2023.out
  tests/examples/Wanju_Yuan_Closed-Loop_Geothermal_Energy_Recovery.out
  tests/examples/example1.out
  tests/examples/example1_addons.out
  tests/examples/example1_outputunits.out
  tests/examples/example4.out
  tests/examples/example9.out
  tests/examples/example_ITC.out
  tests/examples/example_PTC.out
  tests/examples/example_SHR-1.out
  tests/examples/example_SHR-2.out
  tests/examples/example_multiple_gradients.out
  tests/examples/example_overpressure.out
  tests/examples/example_overpressure2.out
Labels: enhancement

#243 Gradients in degC/km; Unit conversion cleanup [3.4.36]
  .bumpversion.cfg
  .cookiecutterrc
  README.rst
  docs/conf.py
  setup.py
  src/geophires_x/Outputs.py
  src/geophires_x/Parameter.py
  src/geophires_x/Reservoir.py
  src/geophires_x/SUTRAWellBores.py
  src/geophires_x/WellBores.py
  src/geophires_x/__init__.py
  src/geophires_x_schema_generator/geophires-request.json
  src/hip_ra/HIP_RA.py
  src/hip_ra_x/hip_ra_x.py
  tests/example1_addons.csv
  tests/examples/Fervo_Norbeck_Latimer_2023.out
  tests/examples/Wanju_Yuan_Closed-Loop_Geothermal_Energy_Recovery.out
  tests/examples/example1.out
  tests/examples/example10_HP.out
  tests/examples/example11_AC.out
  tests/examples/example12_DH.out
  tests/examples/example13.out
  tests/examples/example1_addons.out
  tests/examples/example1_outputunits.out
  tests/examples/example2.out
  tests/examples/example3.out
  tests/examples/example4.out
  tests/examples/example5.out
  tests/examples/example8.out
  tests/examples/example9.out
  tests/examples/example_ITC.out
  tests/examples/example_PTC.out
  tests/examples/example_SHR-1.out
  tests/examples/example_SHR-2.out
  tests/examples/example_multiple_gradients.out
  tests/examples/example_overpressure.out
  tests/examples/example_overpressure2.out
  tests/test_geophires_x.py
  tests/test_geophires_x_client.py
  tests/test_parameter.py
Labels: bug
