Repository NREL/GEOPHIRES-X, pull requests merged in 2025-07, with the labels that each got.

#398 Allow input parameters in CSV
  src/geophires_x_client/geophires_input_parameters.py
  tests/test_geophires_x_client.py
Labels: enhancement, feature request

#401 Parameterize indirect costs [v3.9.34]
  .bumpversion.cfg
  .cookiecutterrc
  README.rst
  docs/conf.py
  setup.py
  src/geophires_x/Economics.py
  src/geophires_x/SBTEconomics.py
  src/geophires_x/__init__.py
  src/geophires_x_client/common.py
  src/geophires_x_schema_generator/__init__.py
  src/geophires_x_schema_generator/geophires-request.json
  src/geophires_x_schema_generator/main.py
  tests/geophires_x_schema_generator_tests/test_generated_schemas.py
  tests/geophires_x_tests/test_economics.py
  tests/geophires_x_tests/test_economics_sam.py
  tests/test_geophires_x.py
Labels: enhancement

#407 Inflation costs during construction [v3.9.42]
  .bumpversion.cfg
  .cookiecutterrc
  .gitignore
  README.rst
  docs/Fervo_Project_Cape-4.md
  docs/SAM-Economic-Models.md
  docs/conf.py
  setup.py
  src/geophires_x/Economics.py
  src/geophires_x/EconomicsSam.py
  src/geophires_x/EconomicsSamCashFlow.py
  src/geophires_x/EconomicsUtils.py
  src/geophires_x/Outputs.py
  src/geophires_x/SurfacePlant.py
  src/geophires_x/__init__.py
  src/geophires_x_client/geophires_x_result.py
  src/geophires_x_schema_generator/geophires-request.json
  src/geophires_x_schema_generator/geophires-result.json
  tests/examples/Fervo_Project_Cape-4.out
  tests/examples/Fervo_Project_Cape-4.txt
  tests/examples/example_SAM-single-owner-PPA-2.out
  tests/examples/example_SAM-single-owner-PPA.out
  tests/geophires_x_tests/generic-egs-case-3_no-inflation-rate-during-construction.txt
  tests/geophires_x_tests/test_economics_sam.py
  tests/test_geophires_x.py
Labels: bug, documentation, enhancement

#409 numpy version fix/upgrade [v3.9.43]
  .bumpversion.cfg
  .cookiecutterrc
  README.rst
  docs/conf.py
  setup.py
  src/geophires_x/GeoPHIRESUtils.py
  src/geophires_x/Model.py
  src/geophires_x/__init__.py
  tests/test_geophires_x.py
Labels: bug

#411 Add-Ons support for SAM Economic Models [v3.9.47]
  .bumpversion.cfg
  .cookiecutterrc
  CHANGELOG.rst
  README.rst
  docs/SAM-Economic-Models.md
  docs/conf.py
  setup.py
  src/geophires_x/Economics.py
  src/geophires_x/EconomicsAddOns.py
  src/geophires_x/EconomicsSam.py
  src/geophires_x/Outputs.py
  src/geophires_x/OutputsAddOns.py
  src/geophires_x/OutputsRich.py
  src/geophires_x/OutputsS_DAC_GT.py
  src/geophires_x/OutputsUtils.py
  src/geophires_x/__init__.py
  src/geophires_x_client/geophires_x_result.py
  src/geophires_x_schema_generator/geophires-result.json
  tests/example1_addons.csv
  tests/examples/example1_addons.out
  tests/examples/example_SAM-single-owner-PPA-3.out
  tests/examples/example_SAM-single-owner-PPA-3.txt
  tests/geophires-result_example-3.csv
  tests/geophires_x_client_tests/test_geophires_x_result.py
  tests/geophires_x_tests/egs-sam-em-add-ons.txt
  tests/geophires_x_tests/test_economics_sam.py
  tests/regenerate-example-result.sh
  tests/regenerate_example_result_csv.py
Labels: bug, documentation, enhancement
